const { Product } = require('../models');

const productData = [
  {
    product_name: 'Honey Crisp Apples',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672299786/products/produce/honey_crisp_apples.jpg',
    price: 1.99,
    stock: 14,
    department_id: 1,
  },
  {
    product_name: 'McIntosh Apples',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672299177/products/produce/mcintosh_apples.png',
    price: 1.99,
    stock: 25,
    department_id: 1,
  },
  {
    product_name: 'Gala Apples',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672299783/products/produce/gala_apples.jpg',
    price: 1.99,
    stock: 12,
    department_id: 1,
  },
  {
    product_name: 'Granny Smith Apples',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672300320/products/produce/granny_smith_apples.jpg',
    price: 1.99,
    stock: 12,
    department_id: 1,
  },
  {
    product_name: 'Bananas',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672300366/products/produce/bananas.png',
    price: 0.99,
    stock: 50,
    department_id: 1,
  },
  {
    product_name: 'Strawberries',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672300438/products/produce/strawberries.png',
    price: 4.99,
    stock: 22,
    department_id: 1,
  },
  {
    product_name: 'Blueberries',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672300487/products/produce/blueberries.png',
    price: 4.79,
    stock: 14,
    department_id: 1,
  },
  {
    product_name: 'Raspberries',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672300583/products/produce/raspberries.png',
    price: 4.99,
    stock: 25,
    department_id: 1,
  },
  {
    product_name: 'Peaches',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672302091/products/produce/peaches.jpg',
    price: 1.29,
    stock: 50,
    department_id: 1,
  },
  {
    product_name: 'Pears',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672302214/products/produce/pears.png',
    price: 1.19,
    stock: 14,
    department_id: 1,
  },
  {
    product_name: 'Oranges',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672302384/products/produce/oranges.png',
    price: 1.00,
    stock: 25,
    department_id: 1,
  },
  {
    product_name: 'Red Grapes',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672302720/products/produce/red_grapes.jpg',
    price: 2.99,
    stock: 12,
    department_id: 1,
  },
  {
    product_name: 'Green Grapes',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672302849/products/produce/green_grapes.png',
    price: 2.99,
    stock: 12,
    department_id: 1,
  },
  {
    product_name: 'Lemons',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672303162/products/produce/lemons.png',
    price: 0.69,
    stock: 50,
    department_id: 1,
  },
  {
    product_name: 'Limes',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672303453/products/produce/limes.jpg',
    price: 0.60,
    stock: 22,
    department_id: 1,
  },
  {
    product_name: 'Broccoli',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672304236/products/produce/broccoli.jpg',
    price: 1.99,
    stock: 14,
    department_id: 1,
  },
  {
    product_name: 'Carrots',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672304370/products/produce/carrots.png',
    price: 2.19,
    stock: 25,
    department_id: 1,
  },
  {
    product_name: 'Cauliflower',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672304722/products/produce/cauliflower.jpg',
    price: 4.99,
    stock: 12,
    department_id: 1,
  },
  {
    product_name: 'Cucumbers',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672304814/products/produce/cucumbers.png',
    price: 1.89,
    stock: 22,
    department_id: 1,
  },
  {
    product_name: 'Green Beans',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672304918/products/produce/green_beans.png',
    price: 4.29,
    stock: 14,
    department_id: 1,
  },
  {
    product_name: 'Lettuce',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672305113/products/produce/lettuce.png',
    price: 1.99,
    stock: 12,
    department_id: 1,
  },
  {
    product_name: 'White Mushrooms',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672305236/products/produce/white_mushrooms.png',
    price: 3.99,
    stock: 42,
    department_id: 1,
  },
  {
    product_name: 'Baby Bella Mushrooms',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672305284/products/produce/baby_bella_mushrooms.png',
    price: 2.99,
    stock: 50,
    department_id: 1,
  },
  {
    product_name: 'White Onions',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672305339/products/produce/white_onions.png',
    price: 1.09,
    stock: 29,
    department_id: 1,
  },
  {
    product_name: 'Red Onions',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672305354/products/produce/red_onions.png',
    price: 1.29,
    stock: 21,
    department_id: 1,
  },
  {
    product_name: 'Yellow Onions',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672305439/products/produce/yellow_onion.png',
    price: 1.49,
    stock: 17,
    department_id: 1,
  },
  {
    product_name: 'Russet Potatoes',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672305623/products/produce/russet_potatoes.png',
    price: 1.19,
    stock: 14,
    department_id: 1,
  },
  {
    product_name: 'Gold Potatoes',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672305623/products/produce/gold_potatoes.png',
    price: 0.79,
    stock: 14,
    department_id: 1,
  },
  {
    product_name: 'Garlic',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672305866/products/produce/garlic.png',
    price: 1.99,
    stock: 25,
    department_id: 1,
  },
  {
    product_name: 'Spinach',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672305923/products/produce/spinach.png',
    price: 1.99,
    stock: 12,
    department_id: 1,
  },
  {
    product_name: 'Tomatoes',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672306429/products/produce/tomatoes.jpg',
    price: 1.99,
    stock: 50,
    department_id: 1,
  },
  {
    product_name: 'Roma Tomatoes',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672306156/products/produce/roma_tomatoes.png',
    price: 1.99,
    stock: 50,
    department_id: 1,
  },
  {
    product_name: 'Milk',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672283084/products/dairy/milk.png',
    price: 4.39,
    stock: 14,
    department_id: 2,
  },
  {
    product_name: 'Oatly Oat Milk',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672286519/products/dairy/oatly_oat_milk.png',
    price: 4.39,
    stock: 25,
    department_id: 2,
  },
  {
    product_name: 'Almond Breeze Almond Milk',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672283801/products/dairy/almond_breeze_almond_milk.png',
    price: 4.19,
    stock: 12,
    department_id: 2,
  },
  {
    product_name: 'Silk Soy Milk',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672286846/products/dairy/silk_soy_milk.png',
    price: 4.79,
    stock: 50,
    department_id: 2,
  },
  {
    product_name: 'Eggs',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672287222/products/dairy/eggs.png',
    price: 5.19,
    stock: 25,
    department_id: 2,
  },
  {
    product_name: 'Butter',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672287555/products/dairy/butter.png',
    price: 6.59,
    stock: 12,
    department_id: 2,
  },
  {
    product_name: 'Cheddar Cheese',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672288194/products/dairy/cheddar_cheese.png',
    price: 6.99,
    stock: 50,
    department_id: 2,
  },
  {
    product_name: 'Mozzarella Cheese',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672288431/products/dairy/mozzarella_cheese.png',
    price: 6.29,
    stock: 22,
    department_id: 2,
  },
  {
    product_name: 'Parmesan Cheese',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672288608/products/dairy/parmesan_cheese.png',
    price: 4.79,
    stock: 14,
    department_id: 2,
  },
  {
    product_name: 'Chobani Greek Yogurt',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672289061/products/dairy/chobani_greek_yogurt.png',
    price: 1.69,
    stock: 22,
    department_id: 2,
  },
  {
    product_name: 'Yoplait Yogurt',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672289290/products/dairy/yoplait_yogurt.png',
    price: 0.89,
    stock: 14,
    department_id: 2,
  },
  {
    product_name: 'Heavy Cream',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672289409/products/dairy/heavy_cream.png',
    price: 2.99,
    stock: 25,
    department_id: 2,
  },
  {
    product_name: 'Half and Half',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672289495/products/dairy/half_and_half.png',
    price: 4.19,
    stock: 12,
    department_id: 2,
  },
  {
    product_name: 'Sour Cream',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672289691/products/dairy/sour_cream.png',
    price: 2.59,
    stock: 50,
    department_id: 2,
  },
  {
    product_name: 'Chicken Breasts',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672289968/products/meat/chicken_breasts.png',
    price: 8.99,
    stock: 22,
    department_id: 3,
  },
  {
    product_name: 'Chicken Thighs',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672167224/products/meat/chicken_thighs.webp',
    price: 8.99,
    stock: 14,
    department_id: 3,
  },
  {
    product_name: 'Ground Beef',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672290057/products/meat/ground_beef.png',
    price: 5.65,
    stock: 14,
    department_id: 3,
  },
  {
    product_name: 'Beef Sirloin Steak',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672290130/products/meat/beef_sirloin_steak.png',
    price: 7.39,
    stock: 14,
    department_id: 3,
  },
  {
    product_name: 'Pork Chops',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672290200/products/meat/pork_chops.png',
    price: 6.59,
    stock: 25,
    department_id: 3,
  },
  {
    product_name: 'Pork Tenderloin',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672290598/products/meat/pork_tenderloin.png',
    price: 4.39,
    stock: 50,
    department_id: 3,
  },
  {
    product_name: 'Salmon Filets',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672291833/products/seafood/salmon_filets.png',
    price: 11.99,
    stock: 22,
    department_id: 4,
  },
  {
    product_name: 'Shrimp',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672292263/products/seafood/shrimp.png',
    price: 7.79,
    stock: 14,
    department_id: 4,
  },
  {
    product_name: 'Cod Filets',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672292351/products/seafood/cod_filets.png',
    price: 10.99,
    stock: 14,
    department_id: 4,
  },
  {
    product_name: 'Tuna Steaks',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672292649/products/seafood/tuna_steaks.png',
    price: 17.39,
    stock: 25,
    department_id: 4,
  },
  {
    product_name: 'Lobster',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672293560/products/seafood/lobster.png',
    price: 15.99,
    stock: 12,
    department_id: 4,
  },
  {
    product_name: 'Crab Legs',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672294863/products/seafood/crab_legs.png',
    price: 14.99,
    stock: 50,
    department_id: 4,
  },
  {
    product_name: 'Rye Bread',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672295130/products/bakery/rye_bread.png',
    price: 6.29,
    stock: 22,
    department_id: 5,
  },
  {
    product_name: 'White Bread',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672295283/products/bakery/white_bread.png',
    price: 6.29,
    stock: 14,
    department_id: 5,
  },
  {
    product_name: 'Whole Wheat Bread',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672295446/products/bakery/whole_wheat_bread.png',
    price: 6.29,
    stock: 14,
    department_id: 5,
  },
  {
    product_name: 'Plain Bagels',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672296624/products/bakery/plain_bagels.jpg',
    price: 2.99,
    stock: 14,
    department_id: 5,
  },
  {
    product_name: 'Everything Bagels',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672296551/products/bakery/everything_bagels.jpg',
    price: 5.99,
    stock: 14,
    department_id: 5,
  },
  {
    product_name: 'English Muffins',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672296734/products/bakery/english_muffins.png',
    price: 5.19,
    stock: 25,
    department_id: 5,
  },
  {
    product_name: 'Pita Bread',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672296808/products/bakery/pita_bread.png',
    price: 3.49,
    stock: 12,
    department_id: 5,
  },
  {
    product_name: 'Brioche Hamburger Buns',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672297500/products/bakery/brioche_hamburger_buns.png~',
    price: 4.49,
    stock: 50,
    department_id: 5,
  },
  {
    product_name: 'Brioche Hot Dog Buns',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672298507/products/bakery/brioche_hot_dog_buns.png',
    price: 2.99,
    stock: 22,
    department_id: 5,
  },
  {
    product_name: 'Kayem Frankfurter Buns',
    product_image: 'https://res.cloudinary.com/grims/image/upload/v1672298515/products/bakery/kayem_frankfurter_buns.png',
    price: 2.99,
    stock: 22,
    department_id: 5,
  },
];



const seedProducts = () => Product.bulkCreate(productData);

module.exports = seedProducts;
